import type { Metadata } from "next";
import localFont from "next/font/local";
import { Abril_Fatface, Lato } from "next/font/google";
import "./globals.css";



const abril =  Abril_Fatface({ subsets: ['latin'], weight: "400" });
const lato = Lato({ subsets: ['latin'], weight: "400" });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${abril.className} antialiased bg-white p-4`}
      >
        {children}
      </body>
    </html>
  );
}
